### ISSUE TITLE
elixir fails to package when multilib is in use

### ISSUE THREAD

**Issue by lsorense** [meta-erlang/meta-erlang#183]
When using multilib, libdir = /usr/lib64 not /usr/lib.  The FILES statements should all be using nonarch_libdir instead of libdir.  Using libdir causes most of the files to get skipped and not packages which of course causes the packaging to fail.

**Comment by lsorense** [comment]
I would have to figure out which parts of the config are relevant.  But it is building for x86_64 with support for x86 32 bit as well, which means the libdir is /usr/lib64 for x86_64 packages and /usr/lib for x86 packages.  Most things are built for x86_64, including erlang and elixir.  But since the elixir stuff is not architecture specific (I hope), it seems it is installing in /usr/lib rather than /usr/lib64.  I suppose that could be a mistake and it is actually using the wrong location for the libraries.

We are pretty much doing what yocto shows here:
https://github.com/intel/luv-yocto/blob/master/meta-skeleton/conf/multilib-example.conf

**Comment by joaohf** [comment]
It might be necessary to set the correct erlang version for rabbitmq, according to https://www.rabbitmq.com/which-erlang.html. I'm testing it too.

Are you getting this error ?

```
| 20:47:36.454 [error] Loading of /build/tmp/work/core2-64-poky-linux/rabbitmq-server/3.9.8-r1/rabbitmq-server-3.9.8/deps/.mix/archives/hex-0.21.3/hex-0.21.3/ebin/Elixir.Hex.Version.beam failed: :badfile               
|                                                                                                                                                                                                                         
|                                                                                                                                                                                                                         
| 20:47:36.455 [notice] Application hex exited: exited in: Hex.Application.start(:normal, [])                                                                                                                             
|     ** (EXIT) an exception was raised:                                                                                                                                                                                  
|         ** (UndefinedFunctionError) function Hex.Version.start/0 is undefined (module Hex.Version is not available)                                                                                                     
|             (hex 0.21.3) Hex.Version.start()                                                                                                                                                                            
|             (hex 0.21.3) lib/hex/application.ex:12: Hex.Application.start/2                                                                                                                                             
|             (kernel 8.4) application_master.erl:293: :application_master.start_it_old/4                                                                                                                                 
|                                                                                                                                                                                                                         
| 20:47:36.463 [notice] Application inets exited: :stopped                                                   
|                                                                                                                                                                                                                         
| 20:47:36.463 [notice] Application ssl exited: :stopped                                                                                                                                                                  
|                                                                                                                                                                                                                         
| 20:47:36.463 [notice] Application public_key exited: :stopped                                                                                                                                                           
|                                                                                                                                                                                                                         
| 20:47:36.463 [notice] Application asn1 exited: :stopped                                                                                                                                                                 
|                                                                                                                                                                                                                         
| 20:47:36.463 [notice] Application crypto exited: :stopped                                                                                                                                                               
| Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"                                                                                             
| ** (MatchError) no match of right hand side value: {:error, {:hex, {:bad_return, {{Hex.Application, :start, [:normal, []]}, {:EXIT, {:undef, [{Hex.Version, :start, [], []}, {Hex.Application, :start, 2, [file: 'lib/h}
|     (hex 0.21.3) lib/hex.ex:5: Hex.start/0                                                                                                                                                                              
|     (mix 1.13.4) lib/mix/hex.ex:59: Mix.Hex.start/0                                                                                                                                                                     
|     (mix 1.13.4) lib/mix/dep/loader.ex:203: Mix.Dep.Loader.with_scm_and_app/4                                                                                                                                           
|     (mix 1.13.4) lib/mix/dep/loader.ex:156: Mix.Dep.Loader.to_dep/3                                                                                                                                                     
|     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2                                                                                                                                                    
|     (mix 1.13.4) lib/mix/dep/loader.ex:373: Mix.Dep.Loader.mix_children/2                                                                                                                                               
|     (mix 1.13.4) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0                                                                                                                                                    
|     (mix 1.13.4) lib/mix/dep/converger.ex:57: Mix.Dep.Converger.all/4                                                                                                                                                   
| make[2]: *** [Makefile:106: escript/rabbitmqctl] Error 1                                                                                                                                                                
| make[2]: *** Waiting for unfinished jobs....                                                                                                                                                                            
| Inlining: inline_size=24 inline_effort=150                                                                                                                                                                              
|  APP    observer_cli.app.src                                                                                                                                                                                            
| make[3]: Leaving directory '/build/tmp/work/core2-64-poky-linux/rabbitmq-server/3.9.8-r1/rabbitmq-server-3.9.8/deps/observer_cli'                                                                                       
| make[2]: Leaving directory '/build/tmp/work/core2-64-poky-linux/rabbitmq-server/3.9.8-r1/rabbitmq-server-3.9.8/deps/rabbitmq_cli'                                                                                       
| make[1]: *** [../../erlang.mk:4512: deps] Error 2
| make[1]: Leaving directory '/build/tmp/work/core2-64-poky-linux/rabbitmq-server/3.9.8-r1/rabbitmq-server-3.9.8/deps/rabbit'                                                                                             
| make: *** [erlang.mk:4512: deps] Error 2
| ERROR: oe_runmake failed                                                                                                                                                                                                
| WARNING: exit code 1 from a shell command.
```

**Comment by lsorense** [comment]
Yes exactly that.  I will try changing to erlang 24.3.3 then.

**Comment by joaohf** [comment]
Try to use these versions:

```
# meta-erlang-elixir
PREFERRED_VERSION_elixir = "1.12%"
PREFERRED_VERSION_elixir-native = "1.12%"
PREFERRED_VERSION_nativesdk-elixir = "1.12%"

# meta-erlang-erlang
PREFERRED_VERSION_erlang = "24.2"
PREFERRED_VERSION_erlang-native = "24.2"
PREFERRED_VERSION_nativesdk-erlang = "24.2"
```

That is the correct combination for rabbitmq 3.9.8 (I'll bump the version later, or at least keep one for each major erlang/elixir combination).

Now, it looks like rabbitmq-server recive also needs change about multilib.

**Comment by lsorense** [comment]
Yeah I did that and now it works nicely if I use the for-master-elixir-nonarch_libdir branch.  Hope that gets merged to kirkstone branch.

**Comment by joaohf** [comment]
Hi.

Done. For master and kirkstone

Thanks.
